### PR TITLE
Change all urls to use current method of access. Closes #118

### LINKED ISSUE #118: Loading non-HTTPS assets into HTTPS pages
The openlayers script on the MHV site is being loaded from a non-https location (because the upstream  doesn't appear to provide one) and giving mixed content errors in chrome.

```
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>
```

Self hosting the asset is probably the quickest solution.

### PR DESCRIPTION
**Pull request by jamiereid**
This is forced to https for our local site.

### CODE REVIEW

**Comment by jamiereid** [comment]
This should be fine (tested locally using http and works ok - can't test https until we push to live server?)

**Comment by cmrn** [comment]
I would suggest explicitly using HTTPS for all URLs that support it, to make sure that HTTPS is used whenever possible (even when the website is run in HTTP mode).

I think that this PR also breaks some links that do not support HTTPS, when makehackvoid.com is accessed using HTTPS. For example, `//ultrakeet.com.au` in  `projects/_posts/2012-03-16-pc-to-pcb.md
` does not support HTTPS, so this link would be broken when that post is loaded with HTTPS.

**Comment by jamiereid** [comment]
No worries, I'll change this PR when I get a chance (hopefully tonight/tomorrow night).

My thought process behind not explicitly using https was simply that we force a redirect on http://makehackvoid.com - but I think your way is better.

**Comment by cmrn** [comment]
Yeah I understand your logic there. I'd suggest a mixed approach - use the `//` syntax for makehackvoid.com URLs, but for external URLs use HTTPS if available, otherwise use HTTP.

**Comment by jamiereid** [comment]
New commit making the changes we discussed :)

**Comment by cmrn** [comment]
Thanks for doing this @jamiereid - must've been a tedious job checking each domain! :+1:

**Pull request merged**
