### PR TITLE
Change to embedded google map - closes #93

### LINKED ISSUE #93: Make the embedded map look nicer
It would be good to either find a theme for the OSM map to make it look a bit nicer, or swap back to Google Maps. As it stands, it's a bit ugly.

### PR DESCRIPTION
**Pull request by jamiereid**

### CODE REVIEW

**Comment by csirac2** [comment]
But! OpenStreetMap! True, let's join the borg. He says, from his @gmail address.

**Comment by csirac2** [comment]
Also I need to be made an organization member in order to merge :P

**Comment by jamiereid** [comment]
You're a member of the org already, but I've added you to the group for the
repo :)

**Comment by csirac2** [comment]
WELL WELL WELL. My github comprehension needs improvement. Thank you for doing it for me :D

**Pull request merged**
